# To update the "client" container below: kubectl set image deployment/client-deployment client=tzetzo/multi_docker-client:v5 
# kubectl get deployments # verify the deployment is applied
# kudectl get pods # verify the pods are applied

apiVersion: apps/v1 # gives us access to specific Object types like Deployment, Service etc
kind: Deployment # Object type we want to create; Deployment is used to setup a set of identical Pods
metadata:
  name: client-deployment  # uniquely identifies this object in combination with the "kind"
spec:
  replicas: 3 # the number of Pod objects this Deployment object should create with the config listed under "template"
  selector:
    matchLabels:
      component: web # tells the Depoyment object the Pods he handles "component: web"; web means "front-end"
  template: # the configuration for every Pod object created by this Deployment object
    metadata:
      labels:
        component: web # used to reference the Pod object
    spec:
      containers:
        - name: client # name of the Container in the Pod
          image: tzetzo/multi_docker-client # the Image from Docker Hub
          ports:
            - containerPort: 3000 # exposes port 3000