# this service object gives access to the "client-deployment" object
# kudectl get services # verify the services are applied

apiVersion: v1 # gives us access to specific Object types like Deployment, Service etc
kind: Service # Object type we want to create; Service is used to setup Networking in K8s Cluster
metadata:
  name: client-cluster-ip-service  # uniquely identifies this object in combination with the "kind"
spec:
  type: ClusterIP # Service type; exposes "component: web" Pods from client-deployment to the orher deployments in the Cluster
  selector:
    component: web # reaches in the K8s Cluster and finds the objects with the label "component: web"
  ports:
    - port: 3000 # for use by other Pods to reach the "component: web" Pod
      targetPort: 3000 # the exposed port on the "component: web" Pod
