# this service object gives access to the "redis-deployment" object
# kudectl get services # verify the services are applied

apiVersion: v1 # gives us access to specific Object types like Deployment, Service etc
kind: Service # Object type we want to create; Service is used to setup Networking in K8s Cluster
metadata:
  name: redis-cluster-ip-service  # used as host name to connect to our Redis Server
spec:
  type: ClusterIP # Service type; exposes "component: redis" Pods from redis-deployment to the orher deployments in the Cluster
  selector:
    component: redis # reaches in the K8s Cluster and finds the objects with the label "component: redis"
  ports:
    - port: 6379 # for use by other Pods to reach the "component: redis" Pod
      targetPort: 6379 # the exposed port on the "component: redis" Pod
