# To update the "server" container below: kubectl set image deployment/server-deployment server=tzetzo/multi_docker-api:v5 
# kubectl get deployments # verify the deployment is applied
# kudectl get pods # verify the pods are applied

apiVersion: apps/v1 # gives us access to specific Object types like Deployment, Service etc
kind: Deployment # Object type we want to create; Deployment is used to setup a set of identical Pods
metadata:
  name: server-deployment  # uniquely identifies this object in combination with the "kind"
spec:
  replicas: 3 # the number of Pod objects this Deployment object should create with the config listed under "template"
  selector:
    matchLabels:
      component: server # tells the Depoyment object the Pods he handles "component: server";
  template: # the configuration for every Pod object created by this Deployment object
    metadata:
      labels:
        component: server # used to reference the Pod object
    spec:
      containers:
        - name: server # name of the Container in the Pod
          image: tzetzo/multi_docker-api # the Image from Docker Hub
          ports:
            - containerPort: 5000 # exposes port 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service # redis-cluster-ip-service.yaml
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service # postgres-cluster-ip-service.yaml
            - name: PGPORT
              value: '5432' # default port for Postgres
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef: 
                  name: pgpassword # should correspond to the name from : kubectl create secret generic pgpassword --from-literal PGPASSWORD=oin88bvd4v5x
                  key: PGPASSWORD # should correspond to the key from : kubectl create secret generic pgpassword --from-literal PGPASSWORD=oin88bvd4v5x